version: "3.8"

services:
  api:
    build: ./api
    container_name: todoapp-backend
    image: batuhangokalp/todoapp-api:latest
    restart: always
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: "mongodb+srv://bbatuhangokalp:uNcM-i_QVTeJsW4@cluster0.xjyiz.mongodb.net/playable-factory"
      JWT_SECRET: "rJ6mK$8xvG5!BqZ2cQeyN@d3X^TpLwM9*UoV1&HsJ4aKg7Et%fY"
    command: sh -c "sleep 5 && node server.js"

  client:
    build: ./client
    container_name: todoapp-frontend
    image: batuhangokalp/todoapp-client:latest
    restart: always
    depends_on:
      - api
    ports:
      - "3000:80"
